"use client";
import { useEffect } from "react";
import Head from "next/head";
import Script from "next/script";

export default async function Unicus() {
  useEffect(() => {
    const unicusButton = document.createElement("unicus-btn");

    unicusButton.addEventListener("OnUnicus:loaded", ({ detail }: any) => {
      console.log("NEXTJS loaded payload 1", detail);
    });

    unicusButton.addEventListener("OnUnicus:details", ({ detail }: any) => {
      console.log("NEXTSJS loaded payload 2", detail);
    });

    unicusButton.addEventListener("OnUnicus:error", ({ detail }: any) => {
      console.log("NEXTJS loaded payload 3", detail);
    });

    unicusButton.addEventListener("OnUnicus:finished", ({ detail }: any) => {
      console.log("NEXTJS loaded payload 4", detail);
    });

    unicusButton.addEventListener("OnUnicus:exit", ({ detail }: any) => {
      console.log("NEXTJS loaded payload 5", detail);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1 className="text-5xl font-bold">Hola</h1>
        {/*  <script src="https://web-button.getmati.com/button.js"></script> */}

        {/* <script
          type="text/javascript"
          src="https://dev-unicusbutton.idunicus.com/sdkButton.js"
        ></script> */}
      </Head>
      <Script src="https://stg-unicusbutton.idunicus.com/sdkButton.js"></Script>
      <main className="w-screen h-screen bg-zinc-200 flex justify-center items-center">
        <unicus-btn
          transactiontype="liveness"
          clientid="ID:171564146-8"
          customerid="OzPToA9Z.2hYZtRmWHyeN26fEGia7QLx1REbMTzc1fgjPJNjKViuFxIZzZriO7="
        />
      </main>
    </div>
  );
}
